name: Create and publish a Docker image for a particular Tag/Release
on:
  push:
    tags: ['v*']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - uses: ko-build/setup-ko@v0.6
      - run: ko build --platform=all --tags ${{  github.ref_name }} --base-import-paths
